### ISSUE TITLE
What is the optimization objective？

### ISSUE THREAD

**Issue by zc300** [bitzj2015/DRL-Networking#2]
Hi,
Thanks for sharing your codes. I also plan to do some work about mobile edge computing, so I'm looking for some research targets currently. But I'm not very familiar with this area so far. 
If you don't mind, could you please simply provide some basic ideas about this work? Such as the problem you deal with or the optimization objectives？
Thank you very much.

**Comment by bitzj2015** [comment]
The objective function is to maximize the accumulative utility of agent/system/player/... in your networking problem. Usually, you will define some utility functions in your networking problems and you want to optimize it.
