### ISSUE TITLE
Code consulting

### ISSUE THREAD

**Issue by lyee-zhong** [bitzj2015/DRL-Networking#3]
Hi,
Thanks for sharing your codes. I recently read a paper on the combination of reinforcement learning and Stackelberg game. The paper is "Free Market of Multi-Leader Multi-Follower Mobile Crowdsensing: An Incentive Mechanism Design by Deep Reinforcement Learning". May I ask if you are the author of this paper?  I see the fourth author in the paper has the same name as you.  Although my research direction is not the same as yours, I really want to learn from this idea. Do you have the code data of this literature? 
It seems that the code you share is also about this. Could you share more information about the code you share now?
Thank you very much!

**Comment by bitzj2015** [comment]
Hi, I am a co-author of that paper. But I don’t have access to the code currently. However, the basic idea of that paper is to design and train a separate DRL model for each leader, which will determine its best incentive strategy for multiple followers. My code shared here is a general PPO algorithm for networking problems. If you want to use, you need to redesign the environment, reward functions, and parameters of PPO agent, according to your problem settings, such as what your state and action are. And I did not improve the PPO algorithm itself. Of course, if you can propose or design some novel algorithms for DRL itself, it will be more novel.
